name: Checkstyle

on: [push, pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run Checkstyle
      run: mvn checkstyle:checkstyle --batch-mode

    - name: Parse Checkstyle Output
      id: parse-checkstyle
      run: |
        echo "-- ls . --"
        ls 
        echo "-- ls target --"
        ls "target"
        # Parse Checkstyle output and set an output variable if WARN messages are found
        if grep -q 'WARN' 'target/checkstyle-result.xml'; then
          echo "Found Warnings"
          echo "::set-output name=has_warnings::true"
        else
          echo "No Warnings found"
          echo "::set-output name=has_warnings::false"
        fi

    - name: Decline Push/Merge on WARN
      if: steps.parse-checkstyle.outputs.has_warnings == 'true'
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'failure',
            target_url: 'https://example.com/checkstyle-warnings',
            description: 'Checkstyle found warnings. Push/Merge declined.',
            context: 'Checkstyle'
          })

    - name: Upload Checkstyle results
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle-results
        path: target/checkstyle-result.xml
