name: Checkstyle

on: [push, pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run Checkstyle
      run: mvn checkstyle:checkstyle --batch-mode

    - name: Parse Checkstyle Output
      id: parse-checkstyle
      run: |
        # Parse Checkstyle output and set an output variable if WARN messages are found
        if grep -Eiq '(severity="warning"|severity="error")' 'target/checkstyle-result.xml'; then
          echo "Found Warnings/Errors"
          grep -Ei '(severity="warning"|severity="error")' 'target/checkstyle-result.xml'
          echo "::set-output name=has_warnings::true"
        else
          echo "No Warnings found"
          echo "::set-output name=has_warnings::false"
        fi

    - name: Set commit status
      if: always()
      uses: actions/github-script@v4
      with:
        has_warnings: ${{ steps.parse-checkstyle.outputs.has_warnings }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const hasWarnings = core.getInput('has_warnings');
          const status = hasWarnings === 'true' ? 'failure' : 'success';
          await github.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: status,
            //target_url: 'https://example.com/checkstyle-warnings',
            context: 'Checkstyle',
            description: status === 'failure' ? 'Checkstyle found warnings or errors' : 'Checkstyle passed'
          });
   
    - name: Set job status to failure if warnings/errors found
      if: steps.parse-checkstyle.outputs.has_warnings == 'true'
      run: exit 1  # This will set the job status to 'failure' if there are warnings/errors

    - name: Upload Checkstyle results
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle-results
        path: target/checkstyle-result.xml
